### ISSUE TITLE
Backtrace piping doesn't work in Python 3

### ISSUE THREAD

**Issue by nir0s** [nir0s/backtrace#7]
The output of an exception that isn't parsed well:

```bash
Traceback (most recent call last):
  File "/home/nir0s/repos/nir0s/backtrace/test2.py", line 4, in moose_bites_kan_be_pretty_nasti
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'certainly_a_non_existing_moose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 123, in <module>
    i = Moose()
  File "test.py", line 25, in __init__
    self.a_moose_once_bit_my_sister()
  File "test.py", line 28, in a_moose_once_bit_my_sister
    _mynd_you()
  File "test.py", line 118, in _mynd_you
    test2.moose_bites_kan_be_pretty_nasti()
  File "/home/nir0s/repos/nir0s/backtrace/test2.py", line 10, in moose_bites_kan_be_pretty_nasti
    moose_func(ex)
  File "/home/nir0s/repos/nir0s/backtrace/test2.py", line 14, in moose_func
    raise raise_moose(ex)
  File "/home/nir0s/repos/nir0s/backtrace/test2.py", line 18, in raise_moose
    raise MooseError(ex)
test2.MooseError: [Errno 2] No such file or directory: 'certainly_a_non_existing_moose'
```

**Comment by nir0s** [comment]
Fixed.
